### ISSUE TITLE
require_relative in client.rb

### ISSUE THREAD

**Issue by NeilNilou** [mahloun/ruby-ipfs-api#4]
remove "require_relative '../../client'"

**Comment by mahloun** [comment]
Thx @NeilNilou

Can you just, in the future, use the markdown syntax for code and links please?

Also, if you are referring to a specific file, can you put a link to it. (You can actually link a specific line of a file).

For example:

Unecessary dependancy to client in [`/lib/api/generic/version.rb`](https://github.com/mahloun/ruby-ipfs-api/blob/master/lib/api/generic/version.rb#L1)
